#Include %A_ScriptDir%\lib\_Input.ahk
#Include %A_ScriptDir%\lib\_MemoryLibrary.ahk
#Include %A_ScriptDir%\lib\_Struct.ahk
#Include %A_ScriptDir%\lib\AhkDllThread.ahk
#Include %A_ScriptDir%\lib\AhkExported.ahk
#Include %A_ScriptDir%\lib\BinRun.ahk
#Include %A_ScriptDir%\lib\CreateScript.ahk
#Include %A_ScriptDir%\lib\DynaRun.ahk
#Include %A_ScriptDir%\lib\GDIP.ahk
#Include %A_ScriptDir%\lib\GetParentDir.ahk
;#Include %A_ScriptDir%\lib\GetProcessWorkingDir.ahk
#Include %A_ScriptDir%\lib\GlobalVarsScript.ahk
#Include %A_ScriptDir%\lib\ini.ahk
#Include %A_ScriptDir%\lib\InjectAhkDll.ahk
;#Include %A_ScriptDir%\lib\MCodeH.ahk
#Include %A_ScriptDir%\lib\ObjTree.ahk
#Include %A_ScriptDir%\lib\SCI.ahk
#Include %A_ScriptDir%\lib\sizeof.ahk
#Include %A_ScriptDir%\lib\TT.ahk
#Include %A_ScriptDir%\lib\WatchDirectory.ahk
#Include %A_ScriptDir%\lib\WinApi.ahk
#Include %A_ScriptDir%\lib\Yaml.ahk
#Include %A_ScriptDir%\lib\Attach.ahk
#Include %A_ScriptDir%\lib\Toolbar.ahk
#Include %A_ScriptDir%\lib\anchor.ahk
